# Generated by Django 3.1.5 on 2021-01-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resolution', models.CharField(blank=True, max_length=200, null=True)),
                ('megapixels', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('consent_doc', models.FileField(blank=True, null=True, upload_to='consent_docs')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('thumbnail_path', models.ImageField(upload_to='thumbnails')),
                ('extension', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('camera_angle', models.CharField(blank=True, max_length=200, null=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.cameras')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.profiles')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.sessions')),
            ],
        ),
        migrations.CreateModel(
            name='VideoClips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='video_clips')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_clips', to='api.videos')),
            ],
        ),
    ]
