# Generated by Django 3.1.5 on 2021-01-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sessions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='consent_doc_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='consent_doc',
            field=models.FileField(blank=True, default='', null=True, upload_to='consent_docs'),
        ),
    ]
