# Generated by Django 3.1.5 on 2021-01-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210130_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='consent_doc_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
