# Generated by Django 3.1.5 on 2021-01-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210130_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.profiles'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.sessions'),
        ),
    ]
