# Generated by Django 3.1.5 on 2021-01-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210131_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraAngles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='videos',
            name='thumbnail_path',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
