# Generated by Django 3.1.5 on 2021-02-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210131_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='thumbnail_path',
            new_name='thumbnail',
        ),
    ]
