export const FETCH_PROFILES = 'FETCH_PROFILES';
export const ADD_PROFILE = 'ADD_PROFILE';
export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';