export const FETCH_PROFILES = 'FETCH_PROFILES';
export const ADD_PROFILE = 'ADD_PROFILE';
export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';

export const FETCH_SESSIONS = 'FETCH_SESSIONS';
export const ADD_SESSION = 'ADD_SESSION';
export const SET_ACTIVE_SESSION = 'SET_ACTIVE_SESSION';
export const DELETE_SESSION = 'DELETE_SESSION';

export const FETCH_VIDEOS = 'FETCH_VIDEOS';
export const ADD_VIDEO = 'ADD_VIDEO';
export const DELETE_VIDEO = 'DELETE_VIDEO';